
// This file has been generated by the GUI designer. Do not modify.
namespace IPChanger.UI
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.Action saveAction;
		
		private global::Gtk.Action openAction;
		
		private global::Gtk.Action newAction;
		
		private global::Gtk.VBox MainVBox;
		
		private global::Gtk.Toolbar toolbar1;
		
		private global::Gtk.HBox NameHBox;
		
		private global::Gtk.Label NameInfo;
		
		private global::Gtk.Label MachineName;
		
		private global::Gtk.HBox NetworkHBox;
		
		private global::Gtk.Label NetworkInfo;
		
		private global::Gtk.Label NetworkName;
		
		private global::Gtk.HSeparator NameSeparator;
		
		private global::Gtk.VBox PropertyVBox;
		
		private global::Gtk.HBox IPHBox;
		
		private global::Gtk.Label IPInfo;
		
		private global::Gtk.Entry ip;
		
		private global::Gtk.Label dot;
		
		private global::Gtk.Entry ip1;
		
		private global::Gtk.Label dot1;
		
		private global::Gtk.Entry ip2;
		
		private global::Gtk.Label dot2;
		
		private global::Gtk.Entry ip3;
		
		private global::Gtk.HBox DNS2HBox;
		
		private global::Gtk.Label DNS2Info;
		
		private global::Gtk.Entry dns20;
		
		private global::Gtk.Label dot12;
		
		private global::Gtk.Entry dns21;
		
		private global::Gtk.Label dot13;
		
		private global::Gtk.Entry dns22;
		
		private global::Gtk.Label dot14;
		
		private global::Gtk.Entry dns23;
		
		private global::Gtk.HBox DNS1HBox1;
		
		private global::Gtk.Label DNS1Info;
		
		private global::Gtk.Entry dns10;
		
		private global::Gtk.Label dot9;
		
		private global::Gtk.Entry dns11;
		
		private global::Gtk.Label dot10;
		
		private global::Gtk.Entry dns12;
		
		private global::Gtk.Label dot11;
		
		private global::Gtk.Entry dns13;
		
		private global::Gtk.HBox GateHBox;
		
		private global::Gtk.Label GateInfo;
		
		private global::Gtk.Entry gate;
		
		private global::Gtk.Label dot6;
		
		private global::Gtk.Entry gate1;
		
		private global::Gtk.Label dot7;
		
		private global::Gtk.Entry gate2;
		
		private global::Gtk.Label dot8;
		
		private global::Gtk.Entry gate3;
		
		private global::Gtk.HBox MaskHBox;
		
		private global::Gtk.Label MaskInfo;
		
		private global::Gtk.Entry mask;
		
		private global::Gtk.Label dot3;
		
		private global::Gtk.Entry mask1;
		
		private global::Gtk.Label dot4;
		
		private global::Gtk.Entry mask2;
		
		private global::Gtk.Label dot5;
		
		private global::Gtk.Entry mask3;
		
		private global::Gtk.HSeparator BttnSeparator;
		
		private global::Gtk.HBox BttnHBox;
		
		private global::Gtk.Button DHCP;
		
		private global::Gtk.Button Static;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget IPChanger.UI.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.saveAction = new global::Gtk.Action ("saveAction", null, null, "gtk-save");
			w1.Add (this.saveAction, null);
			this.openAction = new global::Gtk.Action ("openAction", null, null, "gtk-open");
			w1.Add (this.openAction, null);
			this.newAction = new global::Gtk.Action ("newAction", null, null, "gtk-new");
			w1.Add (this.newAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "IPChanger.UI.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("IP Changer");
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-preferences", global::Gtk.IconSize.Dialog);
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(1));
			this.Resizable = false;
			this.AllowGrow = false;
			this.Gravity = ((global::Gdk.Gravity)(5));
			// Container child IPChanger.UI.MainWindow.Gtk.Container+ContainerChild
			this.MainVBox = new global::Gtk.VBox ();
			this.MainVBox.Name = "MainVBox";
			this.MainVBox.Spacing = 6;
			// Container child MainVBox.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name=\'toolbar1\'><toolitem name=\'newAction\' action=\'newAction\'/><tool" +
			"item name=\'openAction\' action=\'openAction\'/><toolitem name=\'saveAction\' action=\'" +
			"saveAction\'/></toolbar></ui>");
			this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
			this.toolbar1.Name = "toolbar1";
			this.toolbar1.ShowArrow = false;
			this.MainVBox.Add (this.toolbar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.MainVBox [this.toolbar1]));
			w2.Position = 0;
			// Container child MainVBox.Gtk.Box+BoxChild
			this.NameHBox = new global::Gtk.HBox ();
			this.NameHBox.Name = "NameHBox";
			this.NameHBox.Spacing = 6;
			// Container child NameHBox.Gtk.Box+BoxChild
			this.NameInfo = new global::Gtk.Label ();
			this.NameInfo.Name = "NameInfo";
			this.NameInfo.Xalign = 0F;
			this.NameInfo.LabelProp = global::Mono.Unix.Catalog.GetString ("Machine Name:");
			this.NameHBox.Add (this.NameInfo);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.NameHBox [this.NameInfo]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child NameHBox.Gtk.Box+BoxChild
			this.MachineName = new global::Gtk.Label ();
			this.MachineName.Name = "MachineName";
			this.MachineName.Xalign = 1F;
			this.MachineName.LabelProp = global::Mono.Unix.Catalog.GetString ("Name");
			this.MachineName.Selectable = true;
			this.NameHBox.Add (this.MachineName);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.NameHBox [this.MachineName]));
			w4.Position = 1;
			this.MainVBox.Add (this.NameHBox);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.MainVBox [this.NameHBox]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child MainVBox.Gtk.Box+BoxChild
			this.NetworkHBox = new global::Gtk.HBox ();
			this.NetworkHBox.Name = "NetworkHBox";
			this.NetworkHBox.Spacing = 6;
			// Container child NetworkHBox.Gtk.Box+BoxChild
			this.NetworkInfo = new global::Gtk.Label ();
			this.NetworkInfo.Name = "NetworkInfo";
			this.NetworkInfo.Xalign = 0F;
			this.NetworkInfo.LabelProp = global::Mono.Unix.Catalog.GetString ("Network Adapter Name:");
			this.NetworkHBox.Add (this.NetworkInfo);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.NetworkHBox [this.NetworkInfo]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child NetworkHBox.Gtk.Box+BoxChild
			this.NetworkName = new global::Gtk.Label ();
			this.NetworkName.Name = "NetworkName";
			this.NetworkName.Xalign = 1F;
			this.NetworkName.LabelProp = global::Mono.Unix.Catalog.GetString ("Name");
			this.NetworkName.Selectable = true;
			this.NetworkHBox.Add (this.NetworkName);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.NetworkHBox [this.NetworkName]));
			w7.Position = 1;
			this.MainVBox.Add (this.NetworkHBox);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.MainVBox [this.NetworkHBox]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			// Container child MainVBox.Gtk.Box+BoxChild
			this.NameSeparator = new global::Gtk.HSeparator ();
			this.NameSeparator.Name = "NameSeparator";
			this.MainVBox.Add (this.NameSeparator);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.MainVBox [this.NameSeparator]));
			w9.Position = 3;
			w9.Expand = false;
			w9.Fill = false;
			// Container child MainVBox.Gtk.Box+BoxChild
			this.PropertyVBox = new global::Gtk.VBox ();
			this.PropertyVBox.Name = "PropertyVBox";
			this.PropertyVBox.Spacing = 6;
			// Container child PropertyVBox.Gtk.Box+BoxChild
			this.IPHBox = new global::Gtk.HBox ();
			this.IPHBox.Name = "IPHBox";
			this.IPHBox.Spacing = 6;
			// Container child IPHBox.Gtk.Box+BoxChild
			this.IPInfo = new global::Gtk.Label ();
			this.IPInfo.Name = "IPInfo";
			this.IPInfo.Xalign = 0F;
			this.IPInfo.LabelProp = global::Mono.Unix.Catalog.GetString ("IP:");
			this.IPHBox.Add (this.IPInfo);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.IPHBox [this.IPInfo]));
			w10.Position = 0;
			// Container child IPHBox.Gtk.Box+BoxChild
			this.ip = new global::Gtk.Entry ();
			this.ip.CanFocus = true;
			this.ip.Name = "ip";
			this.ip.IsEditable = true;
			this.ip.WidthChars = 3;
			this.ip.MaxLength = 3;
			this.ip.InvisibleChar = '●';
			this.IPHBox.Add (this.ip);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.IPHBox [this.ip]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child IPHBox.Gtk.Box+BoxChild
			this.dot = new global::Gtk.Label ();
			this.dot.Name = "dot";
			this.dot.LabelProp = global::Mono.Unix.Catalog.GetString (".");
			this.IPHBox.Add (this.dot);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.IPHBox [this.dot]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			// Container child IPHBox.Gtk.Box+BoxChild
			this.ip1 = new global::Gtk.Entry ();
			this.ip1.CanFocus = true;
			this.ip1.Name = "ip1";
			this.ip1.IsEditable = true;
			this.ip1.WidthChars = 3;
			this.ip1.MaxLength = 3;
			this.ip1.InvisibleChar = '●';
			this.IPHBox.Add (this.ip1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.IPHBox [this.ip1]));
			w13.Position = 3;
			w13.Expand = false;
			w13.Fill = false;
			// Container child IPHBox.Gtk.Box+BoxChild
			this.dot1 = new global::Gtk.Label ();
			this.dot1.Name = "dot1";
			this.dot1.LabelProp = global::Mono.Unix.Catalog.GetString (".");
			this.IPHBox.Add (this.dot1);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.IPHBox [this.dot1]));
			w14.Position = 4;
			w14.Expand = false;
			w14.Fill = false;
			// Container child IPHBox.Gtk.Box+BoxChild
			this.ip2 = new global::Gtk.Entry ();
			this.ip2.CanFocus = true;
			this.ip2.Name = "ip2";
			this.ip2.IsEditable = true;
			this.ip2.WidthChars = 3;
			this.ip2.MaxLength = 3;
			this.ip2.InvisibleChar = '●';
			this.IPHBox.Add (this.ip2);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.IPHBox [this.ip2]));
			w15.Position = 5;
			w15.Expand = false;
			w15.Fill = false;
			// Container child IPHBox.Gtk.Box+BoxChild
			this.dot2 = new global::Gtk.Label ();
			this.dot2.Name = "dot2";
			this.dot2.LabelProp = global::Mono.Unix.Catalog.GetString (".");
			this.IPHBox.Add (this.dot2);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.IPHBox [this.dot2]));
			w16.Position = 6;
			w16.Expand = false;
			w16.Fill = false;
			// Container child IPHBox.Gtk.Box+BoxChild
			this.ip3 = new global::Gtk.Entry ();
			this.ip3.CanFocus = true;
			this.ip3.Name = "ip3";
			this.ip3.IsEditable = true;
			this.ip3.WidthChars = 3;
			this.ip3.MaxLength = 3;
			this.ip3.InvisibleChar = '●';
			this.IPHBox.Add (this.ip3);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.IPHBox [this.ip3]));
			w17.Position = 7;
			w17.Expand = false;
			w17.Fill = false;
			this.PropertyVBox.Add (this.IPHBox);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.PropertyVBox [this.IPHBox]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child PropertyVBox.Gtk.Box+BoxChild
			this.DNS2HBox = new global::Gtk.HBox ();
			this.DNS2HBox.Name = "DNS2HBox";
			this.DNS2HBox.Spacing = 6;
			// Container child DNS2HBox.Gtk.Box+BoxChild
			this.DNS2Info = new global::Gtk.Label ();
			this.DNS2Info.Name = "DNS2Info";
			this.DNS2Info.Xalign = 0F;
			this.DNS2Info.LabelProp = global::Mono.Unix.Catalog.GetString ("Alternate DNS Server:");
			this.DNS2HBox.Add (this.DNS2Info);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.DNS2HBox [this.DNS2Info]));
			w19.Position = 0;
			// Container child DNS2HBox.Gtk.Box+BoxChild
			this.dns20 = new global::Gtk.Entry ();
			this.dns20.CanFocus = true;
			this.dns20.Name = "dns20";
			this.dns20.IsEditable = true;
			this.dns20.WidthChars = 3;
			this.dns20.MaxLength = 3;
			this.dns20.InvisibleChar = '●';
			this.DNS2HBox.Add (this.dns20);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.DNS2HBox [this.dns20]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child DNS2HBox.Gtk.Box+BoxChild
			this.dot12 = new global::Gtk.Label ();
			this.dot12.Name = "dot12";
			this.dot12.LabelProp = global::Mono.Unix.Catalog.GetString (".");
			this.DNS2HBox.Add (this.dot12);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.DNS2HBox [this.dot12]));
			w21.Position = 2;
			w21.Expand = false;
			w21.Fill = false;
			// Container child DNS2HBox.Gtk.Box+BoxChild
			this.dns21 = new global::Gtk.Entry ();
			this.dns21.CanFocus = true;
			this.dns21.Name = "dns21";
			this.dns21.IsEditable = true;
			this.dns21.WidthChars = 3;
			this.dns21.MaxLength = 3;
			this.dns21.InvisibleChar = '●';
			this.DNS2HBox.Add (this.dns21);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.DNS2HBox [this.dns21]));
			w22.Position = 3;
			w22.Expand = false;
			w22.Fill = false;
			// Container child DNS2HBox.Gtk.Box+BoxChild
			this.dot13 = new global::Gtk.Label ();
			this.dot13.Name = "dot13";
			this.dot13.LabelProp = global::Mono.Unix.Catalog.GetString (".");
			this.DNS2HBox.Add (this.dot13);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.DNS2HBox [this.dot13]));
			w23.Position = 4;
			w23.Expand = false;
			w23.Fill = false;
			// Container child DNS2HBox.Gtk.Box+BoxChild
			this.dns22 = new global::Gtk.Entry ();
			this.dns22.CanFocus = true;
			this.dns22.Name = "dns22";
			this.dns22.IsEditable = true;
			this.dns22.WidthChars = 3;
			this.dns22.MaxLength = 3;
			this.dns22.InvisibleChar = '●';
			this.DNS2HBox.Add (this.dns22);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.DNS2HBox [this.dns22]));
			w24.Position = 5;
			w24.Expand = false;
			w24.Fill = false;
			// Container child DNS2HBox.Gtk.Box+BoxChild
			this.dot14 = new global::Gtk.Label ();
			this.dot14.Name = "dot14";
			this.dot14.LabelProp = global::Mono.Unix.Catalog.GetString (".");
			this.DNS2HBox.Add (this.dot14);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.DNS2HBox [this.dot14]));
			w25.Position = 6;
			w25.Expand = false;
			w25.Fill = false;
			// Container child DNS2HBox.Gtk.Box+BoxChild
			this.dns23 = new global::Gtk.Entry ();
			this.dns23.CanFocus = true;
			this.dns23.Name = "dns23";
			this.dns23.IsEditable = true;
			this.dns23.WidthChars = 3;
			this.dns23.MaxLength = 3;
			this.dns23.InvisibleChar = '●';
			this.DNS2HBox.Add (this.dns23);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.DNS2HBox [this.dns23]));
			w26.Position = 7;
			w26.Expand = false;
			w26.Fill = false;
			this.PropertyVBox.Add (this.DNS2HBox);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.PropertyVBox [this.DNS2HBox]));
			w27.PackType = ((global::Gtk.PackType)(1));
			w27.Position = 1;
			w27.Expand = false;
			w27.Fill = false;
			// Container child PropertyVBox.Gtk.Box+BoxChild
			this.DNS1HBox1 = new global::Gtk.HBox ();
			this.DNS1HBox1.Name = "DNS1HBox1";
			this.DNS1HBox1.Spacing = 6;
			// Container child DNS1HBox1.Gtk.Box+BoxChild
			this.DNS1Info = new global::Gtk.Label ();
			this.DNS1Info.Name = "DNS1Info";
			this.DNS1Info.Xalign = 0F;
			this.DNS1Info.LabelProp = global::Mono.Unix.Catalog.GetString ("Preferred DNS Server:");
			this.DNS1HBox1.Add (this.DNS1Info);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.DNS1HBox1 [this.DNS1Info]));
			w28.Position = 0;
			// Container child DNS1HBox1.Gtk.Box+BoxChild
			this.dns10 = new global::Gtk.Entry ();
			this.dns10.CanFocus = true;
			this.dns10.Name = "dns10";
			this.dns10.IsEditable = true;
			this.dns10.WidthChars = 3;
			this.dns10.MaxLength = 3;
			this.dns10.InvisibleChar = '●';
			this.DNS1HBox1.Add (this.dns10);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.DNS1HBox1 [this.dns10]));
			w29.Position = 1;
			w29.Expand = false;
			w29.Fill = false;
			// Container child DNS1HBox1.Gtk.Box+BoxChild
			this.dot9 = new global::Gtk.Label ();
			this.dot9.Name = "dot9";
			this.dot9.LabelProp = global::Mono.Unix.Catalog.GetString (".");
			this.DNS1HBox1.Add (this.dot9);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.DNS1HBox1 [this.dot9]));
			w30.Position = 2;
			w30.Expand = false;
			w30.Fill = false;
			// Container child DNS1HBox1.Gtk.Box+BoxChild
			this.dns11 = new global::Gtk.Entry ();
			this.dns11.CanFocus = true;
			this.dns11.Name = "dns11";
			this.dns11.IsEditable = true;
			this.dns11.WidthChars = 3;
			this.dns11.MaxLength = 3;
			this.dns11.InvisibleChar = '●';
			this.DNS1HBox1.Add (this.dns11);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.DNS1HBox1 [this.dns11]));
			w31.Position = 3;
			w31.Expand = false;
			w31.Fill = false;
			// Container child DNS1HBox1.Gtk.Box+BoxChild
			this.dot10 = new global::Gtk.Label ();
			this.dot10.Name = "dot10";
			this.dot10.LabelProp = global::Mono.Unix.Catalog.GetString (".");
			this.DNS1HBox1.Add (this.dot10);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.DNS1HBox1 [this.dot10]));
			w32.Position = 4;
			w32.Expand = false;
			w32.Fill = false;
			// Container child DNS1HBox1.Gtk.Box+BoxChild
			this.dns12 = new global::Gtk.Entry ();
			this.dns12.CanFocus = true;
			this.dns12.Name = "dns12";
			this.dns12.IsEditable = true;
			this.dns12.WidthChars = 3;
			this.dns12.MaxLength = 3;
			this.dns12.InvisibleChar = '●';
			this.DNS1HBox1.Add (this.dns12);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.DNS1HBox1 [this.dns12]));
			w33.Position = 5;
			w33.Expand = false;
			w33.Fill = false;
			// Container child DNS1HBox1.Gtk.Box+BoxChild
			this.dot11 = new global::Gtk.Label ();
			this.dot11.Name = "dot11";
			this.dot11.LabelProp = global::Mono.Unix.Catalog.GetString (".");
			this.DNS1HBox1.Add (this.dot11);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.DNS1HBox1 [this.dot11]));
			w34.Position = 6;
			w34.Expand = false;
			w34.Fill = false;
			// Container child DNS1HBox1.Gtk.Box+BoxChild
			this.dns13 = new global::Gtk.Entry ();
			this.dns13.CanFocus = true;
			this.dns13.Name = "dns13";
			this.dns13.IsEditable = true;
			this.dns13.WidthChars = 3;
			this.dns13.MaxLength = 3;
			this.dns13.InvisibleChar = '●';
			this.DNS1HBox1.Add (this.dns13);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.DNS1HBox1 [this.dns13]));
			w35.Position = 7;
			w35.Expand = false;
			w35.Fill = false;
			this.PropertyVBox.Add (this.DNS1HBox1);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.PropertyVBox [this.DNS1HBox1]));
			w36.PackType = ((global::Gtk.PackType)(1));
			w36.Position = 2;
			w36.Expand = false;
			w36.Fill = false;
			// Container child PropertyVBox.Gtk.Box+BoxChild
			this.GateHBox = new global::Gtk.HBox ();
			this.GateHBox.Name = "GateHBox";
			this.GateHBox.Spacing = 6;
			// Container child GateHBox.Gtk.Box+BoxChild
			this.GateInfo = new global::Gtk.Label ();
			this.GateInfo.Name = "GateInfo";
			this.GateInfo.Xalign = 0F;
			this.GateInfo.LabelProp = global::Mono.Unix.Catalog.GetString ("Default Gateway:");
			this.GateHBox.Add (this.GateInfo);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.GateHBox [this.GateInfo]));
			w37.Position = 0;
			// Container child GateHBox.Gtk.Box+BoxChild
			this.gate = new global::Gtk.Entry ();
			this.gate.CanFocus = true;
			this.gate.Name = "gate";
			this.gate.IsEditable = true;
			this.gate.WidthChars = 3;
			this.gate.MaxLength = 3;
			this.gate.InvisibleChar = '●';
			this.GateHBox.Add (this.gate);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.GateHBox [this.gate]));
			w38.Position = 1;
			w38.Expand = false;
			w38.Fill = false;
			// Container child GateHBox.Gtk.Box+BoxChild
			this.dot6 = new global::Gtk.Label ();
			this.dot6.Name = "dot6";
			this.dot6.LabelProp = global::Mono.Unix.Catalog.GetString (".");
			this.GateHBox.Add (this.dot6);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.GateHBox [this.dot6]));
			w39.Position = 2;
			w39.Expand = false;
			w39.Fill = false;
			// Container child GateHBox.Gtk.Box+BoxChild
			this.gate1 = new global::Gtk.Entry ();
			this.gate1.CanFocus = true;
			this.gate1.Name = "gate1";
			this.gate1.IsEditable = true;
			this.gate1.WidthChars = 3;
			this.gate1.MaxLength = 3;
			this.gate1.InvisibleChar = '●';
			this.GateHBox.Add (this.gate1);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.GateHBox [this.gate1]));
			w40.Position = 3;
			w40.Expand = false;
			w40.Fill = false;
			// Container child GateHBox.Gtk.Box+BoxChild
			this.dot7 = new global::Gtk.Label ();
			this.dot7.Name = "dot7";
			this.dot7.LabelProp = global::Mono.Unix.Catalog.GetString (".");
			this.GateHBox.Add (this.dot7);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.GateHBox [this.dot7]));
			w41.Position = 4;
			w41.Expand = false;
			w41.Fill = false;
			// Container child GateHBox.Gtk.Box+BoxChild
			this.gate2 = new global::Gtk.Entry ();
			this.gate2.CanFocus = true;
			this.gate2.Name = "gate2";
			this.gate2.IsEditable = true;
			this.gate2.WidthChars = 3;
			this.gate2.MaxLength = 3;
			this.gate2.InvisibleChar = '●';
			this.GateHBox.Add (this.gate2);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.GateHBox [this.gate2]));
			w42.Position = 5;
			w42.Expand = false;
			w42.Fill = false;
			// Container child GateHBox.Gtk.Box+BoxChild
			this.dot8 = new global::Gtk.Label ();
			this.dot8.Name = "dot8";
			this.dot8.LabelProp = global::Mono.Unix.Catalog.GetString (".");
			this.GateHBox.Add (this.dot8);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.GateHBox [this.dot8]));
			w43.Position = 6;
			w43.Expand = false;
			w43.Fill = false;
			// Container child GateHBox.Gtk.Box+BoxChild
			this.gate3 = new global::Gtk.Entry ();
			this.gate3.CanFocus = true;
			this.gate3.Name = "gate3";
			this.gate3.IsEditable = true;
			this.gate3.WidthChars = 3;
			this.gate3.MaxLength = 3;
			this.gate3.InvisibleChar = '●';
			this.GateHBox.Add (this.gate3);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.GateHBox [this.gate3]));
			w44.Position = 7;
			w44.Expand = false;
			w44.Fill = false;
			this.PropertyVBox.Add (this.GateHBox);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.PropertyVBox [this.GateHBox]));
			w45.PackType = ((global::Gtk.PackType)(1));
			w45.Position = 3;
			w45.Expand = false;
			w45.Fill = false;
			// Container child PropertyVBox.Gtk.Box+BoxChild
			this.MaskHBox = new global::Gtk.HBox ();
			this.MaskHBox.Name = "MaskHBox";
			this.MaskHBox.Spacing = 6;
			// Container child MaskHBox.Gtk.Box+BoxChild
			this.MaskInfo = new global::Gtk.Label ();
			this.MaskInfo.Name = "MaskInfo";
			this.MaskInfo.Xalign = 0F;
			this.MaskInfo.LabelProp = global::Mono.Unix.Catalog.GetString ("Subnet Mask:");
			this.MaskHBox.Add (this.MaskInfo);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.MaskHBox [this.MaskInfo]));
			w46.Position = 0;
			// Container child MaskHBox.Gtk.Box+BoxChild
			this.mask = new global::Gtk.Entry ();
			this.mask.CanFocus = true;
			this.mask.Name = "mask";
			this.mask.IsEditable = true;
			this.mask.WidthChars = 3;
			this.mask.MaxLength = 3;
			this.mask.InvisibleChar = '●';
			this.MaskHBox.Add (this.mask);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.MaskHBox [this.mask]));
			w47.Position = 1;
			w47.Expand = false;
			w47.Fill = false;
			// Container child MaskHBox.Gtk.Box+BoxChild
			this.dot3 = new global::Gtk.Label ();
			this.dot3.Name = "dot3";
			this.dot3.LabelProp = global::Mono.Unix.Catalog.GetString (".");
			this.MaskHBox.Add (this.dot3);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.MaskHBox [this.dot3]));
			w48.Position = 2;
			w48.Expand = false;
			w48.Fill = false;
			// Container child MaskHBox.Gtk.Box+BoxChild
			this.mask1 = new global::Gtk.Entry ();
			this.mask1.CanFocus = true;
			this.mask1.Name = "mask1";
			this.mask1.IsEditable = true;
			this.mask1.WidthChars = 3;
			this.mask1.MaxLength = 3;
			this.mask1.InvisibleChar = '●';
			this.MaskHBox.Add (this.mask1);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.MaskHBox [this.mask1]));
			w49.Position = 3;
			w49.Expand = false;
			w49.Fill = false;
			// Container child MaskHBox.Gtk.Box+BoxChild
			this.dot4 = new global::Gtk.Label ();
			this.dot4.Name = "dot4";
			this.dot4.LabelProp = global::Mono.Unix.Catalog.GetString (".");
			this.MaskHBox.Add (this.dot4);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.MaskHBox [this.dot4]));
			w50.Position = 4;
			w50.Expand = false;
			w50.Fill = false;
			// Container child MaskHBox.Gtk.Box+BoxChild
			this.mask2 = new global::Gtk.Entry ();
			this.mask2.CanFocus = true;
			this.mask2.Name = "mask2";
			this.mask2.IsEditable = true;
			this.mask2.WidthChars = 3;
			this.mask2.MaxLength = 3;
			this.mask2.InvisibleChar = '●';
			this.MaskHBox.Add (this.mask2);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.MaskHBox [this.mask2]));
			w51.Position = 5;
			w51.Expand = false;
			w51.Fill = false;
			// Container child MaskHBox.Gtk.Box+BoxChild
			this.dot5 = new global::Gtk.Label ();
			this.dot5.Name = "dot5";
			this.dot5.LabelProp = global::Mono.Unix.Catalog.GetString (".");
			this.MaskHBox.Add (this.dot5);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.MaskHBox [this.dot5]));
			w52.Position = 6;
			w52.Expand = false;
			w52.Fill = false;
			// Container child MaskHBox.Gtk.Box+BoxChild
			this.mask3 = new global::Gtk.Entry ();
			this.mask3.CanFocus = true;
			this.mask3.Name = "mask3";
			this.mask3.IsEditable = true;
			this.mask3.WidthChars = 3;
			this.mask3.MaxLength = 3;
			this.mask3.InvisibleChar = '●';
			this.MaskHBox.Add (this.mask3);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.MaskHBox [this.mask3]));
			w53.Position = 7;
			w53.Expand = false;
			w53.Fill = false;
			this.PropertyVBox.Add (this.MaskHBox);
			global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.PropertyVBox [this.MaskHBox]));
			w54.PackType = ((global::Gtk.PackType)(1));
			w54.Position = 4;
			w54.Expand = false;
			w54.Fill = false;
			this.MainVBox.Add (this.PropertyVBox);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.MainVBox [this.PropertyVBox]));
			w55.Position = 4;
			w55.Expand = false;
			w55.Fill = false;
			// Container child MainVBox.Gtk.Box+BoxChild
			this.BttnSeparator = new global::Gtk.HSeparator ();
			this.BttnSeparator.Name = "BttnSeparator";
			this.MainVBox.Add (this.BttnSeparator);
			global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.MainVBox [this.BttnSeparator]));
			w56.Position = 5;
			w56.Expand = false;
			w56.Fill = false;
			// Container child MainVBox.Gtk.Box+BoxChild
			this.BttnHBox = new global::Gtk.HBox ();
			this.BttnHBox.Name = "BttnHBox";
			this.BttnHBox.Spacing = 6;
			// Container child BttnHBox.Gtk.Box+BoxChild
			this.DHCP = new global::Gtk.Button ();
			global::Gtk.Tooltips w57 = new Gtk.Tooltips ();
			w57.SetTip (this.DHCP, "Sets this computer to DHCP", "Sets this computer to DHCP");
			this.DHCP.CanFocus = true;
			this.DHCP.Name = "DHCP";
			this.DHCP.UseUnderline = true;
			this.DHCP.Label = global::Mono.Unix.Catalog.GetString ("Set DHCP");
			this.BttnHBox.Add (this.DHCP);
			global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.BttnHBox [this.DHCP]));
			w58.Position = 0;
			// Container child BttnHBox.Gtk.Box+BoxChild
			this.Static = new global::Gtk.Button ();
			w57.SetTip (this.Static, "Sets this computer to Static using the above settings", "Sets this computer to Static using the above settings");
			this.Static.CanFocus = true;
			this.Static.Name = "Static";
			this.Static.UseUnderline = true;
			this.Static.Label = global::Mono.Unix.Catalog.GetString ("Set Static");
			this.BttnHBox.Add (this.Static);
			global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.BttnHBox [this.Static]));
			w59.Position = 1;
			this.MainVBox.Add (this.BttnHBox);
			global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.MainVBox [this.BttnHBox]));
			w60.Position = 6;
			w60.Expand = false;
			w60.Fill = false;
			this.Add (this.MainVBox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 303;
			this.DefaultHeight = 320;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.saveAction.Activated += new global::System.EventHandler (this.OnSave);
			this.openAction.Activated += new global::System.EventHandler (this.OnLoad);
			this.newAction.Activated += new global::System.EventHandler (this.OnNew);
			this.ip.Changed += new global::System.EventHandler (this.OnEntryChanged);
			this.ip1.Changed += new global::System.EventHandler (this.OnEntryChanged);
			this.ip2.Changed += new global::System.EventHandler (this.OnEntryChanged);
			this.ip3.Changed += new global::System.EventHandler (this.OnEntryChanged);
			this.mask.Changed += new global::System.EventHandler (this.OnEntryChanged);
			this.mask1.Changed += new global::System.EventHandler (this.OnEntryChanged);
			this.mask2.Changed += new global::System.EventHandler (this.OnEntryChanged);
			this.mask3.Changed += new global::System.EventHandler (this.OnEntryChanged);
			this.gate.Changed += new global::System.EventHandler (this.OnEntryChanged);
			this.gate1.Changed += new global::System.EventHandler (this.OnEntryChanged);
			this.gate2.Changed += new global::System.EventHandler (this.OnEntryChanged);
			this.gate3.Changed += new global::System.EventHandler (this.OnEntryChanged);
			this.dns10.Changed += new global::System.EventHandler (this.OnEntryChanged);
			this.dns11.Changed += new global::System.EventHandler (this.OnEntryChanged);
			this.dns12.Changed += new global::System.EventHandler (this.OnEntryChanged);
			this.dns13.Changed += new global::System.EventHandler (this.OnEntryChanged);
			this.dns20.Changed += new global::System.EventHandler (this.OnEntryChanged);
			this.dns21.Changed += new global::System.EventHandler (this.OnEntryChanged);
			this.dns22.Changed += new global::System.EventHandler (this.OnEntryChanged);
			this.dns23.Changed += new global::System.EventHandler (this.OnEntryChanged);
			this.DHCP.Clicked += new global::System.EventHandler (this.OnDHCPClicked);
			this.Static.Clicked += new global::System.EventHandler (this.OnStaticClicked);
		}
	}
}
